apiVersion: v1
kind: Service
metadata:
  name: comfyui-engine
  labels:
    {{- include "asgardian.labels" . | nindent 4 }}
spec:
  ports: [{ name: comfyui, port: 8188, protocol: TCP, targetPort: 8188 }]
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: comfyui-engine-static
  labels:
    kubernetes.io/service-name: comfyui-engine
    {{- include "asgardian.labels" . | nindent 4 }}
addressType: IPv4
ports: [{ name: comfyui, protocol: TCP, port: 8188 }]
endpoints:
  - addresses: [{{ .Values.config.comfyEngineAddress | quote }}]
    conditions: { ready: true }
