apiVersion: v1
kind: Secret
metadata:
  name: asgardian-runtime
  labels:
    {{- include "asgardian.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ printf "postgresql+psycopg://%s:%s@asgardian-postgres:5432/%s" .Values.postgres.username .Values.postgres.password .Values.postgres.database | quote }}
  postgres-password: {{ .Values.postgres.password | quote }}
  s3-access-key: {{ .Values.config.s3AccessKey | quote }}
  s3-secret-key: {{ .Values.config.s3SecretKey | quote }}
